-- 1. Tabela de Capítulos
create table public.chapters (
  id bigint generated by default as identity primary key,
  name text not null,
  acronym text not null, -- Ex: RAS, CS
  description text,
  color_theme text, -- Ex: "from-blue-500 to-indigo-600"
  icon_name text, -- Nome do ícone Lucide
  cover_image_url text,
  calendar_url text, -- Link para o arquivo .ics público
  email text, -- E-mail de contato do capítulo
  keywords text[], -- Keywords/Hashtags para vTools
  content_url text, -- JSON string para galeria de links [{'title': '', 'url': '', 'emoji': ''}]
  members_count int default 0,
  projects_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Tabela de Permissões (RBAC) [NOVA]
create table public.permissions (
  id bigint generated by default as identity primary key,
  slug text not null unique, -- 'admin', 'chair', 'manager', 'member', 'external'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Seed Default Permissions
insert into public.permissions (slug)
values 
  ('admin'),
  ('chair'),
  ('manager'),
  ('member'),
  ('external');

-- 3. Tabela de Usuários (Profiles)
create table public.profiles (
  id bigint generated by default as identity primary key,
  auth_id uuid references auth.users(id), -- Link com Supabase Auth
  full_name text not null,
  email text not null,
  role text, -- Cargo Principal / Título de Exibição (ex: Presidente do Ramo)
  avatar_initials text,
  -- REMOVIDO: chapter_ids, chapter_roles (Normalizado em profile_chapters)
  matricula text,
  birth_date date,
  skills text[], -- Array de strings para habilidades
  photo_url text,
  bio text, -- Texto longo em Markdown para o currículo
  notes text,
  membership_number text,
  cover_config text,
  social_links jsonb default '{}'::jsonb, -- { linkedin: '', github: '', instagram: '' }
  phone text, -- NOVO: Telefone
  cpf text[], -- NOVO: CPF (Visível apenas para Admin via RSL - *Requer tabela separada para RSL estrito, mantido aqui por solicitação*)
  ieee_membership_date text, -- NOVO: Data de entrada/saída (Mês/Ano)
  course text, -- NOVO: Curso
  fcm_token text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Index para busca rápida por usuário logado
create unique index idx_profiles_auth_id on public.profiles(auth_id);

-- 4. Tabela de Membros dos Capítulos [NOVA]
create table public.profile_chapters (
  id bigint generated by default as identity primary key,
  profile_id bigint references public.profiles(id) on delete cascade,
  chapter_id bigint references public.chapters(id) on delete cascade,
  role text, -- Display Title (e.g. "Diretor de Projetos")
  permission_slug text references public.permissions(slug), -- RBAC
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(profile_id, chapter_id)
);

-- 5. Tabela de Projetos
create table public.projects (
  id bigint generated by default as identity primary key,
  public_id text unique, -- NanoID (Ex: 'x7B3z')
  name text not null,
  description text,
  status text, -- 'Em Andamento', 'Planejamento'
  progress int default 0,
  start_date date,
  end_date date,
  is_partnership boolean default false,
  -- REMOVIDO: owner_ids, team_ids, chapter_ids (Normalizado em tabelas de junção)
  tags text[], -- Array de strings para tags
  checkpoints jsonb default '[]'::jsonb, -- Array de {title: string, date: string}
  notes text, -- Anotações gerais do projeto (textarea)
  content_url text, -- JSON string para galeria de links [{'title': '', 'url': '', 'emoji': ''}]
  color_theme text, -- Gradiente visual 
  cover_image text, -- URL da imagem de capa
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. Tabela de Membros do Projeto [NOVA]
create table public.project_members (
  project_id bigint references public.projects(id) on delete cascade,
  profile_id bigint references public.profiles(id) on delete cascade,
  is_owner boolean default false, -- Flag para diferenciar Dono de Membro
  created_at timestamp with time zone default timezone('utc'::text, now()),
  primary key (project_id, profile_id)
);

-- 7. Tabela de Capítulos do Projeto [NOVA]
create table public.project_chapters (
  project_id bigint references public.projects(id) on delete cascade,
  chapter_id bigint references public.chapters(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  primary key (project_id, chapter_id)
);

-- 8. Tabela de Tarefas
create table public.tasks (
  id bigint generated by default as identity primary key,
  public_id text unique, -- NanoID curto
  title text not null,
  description text,
  status text check (status in ('todo', 'doing', 'review', 'done', 'archived')),
  priority text, -- 'alta', 'media', 'baixa', 'urgente'
  start_date date default CURRENT_DATE,
  deadline date,
  tags text[],
  attachments_count int default 0,
  content_url text, -- URL para iframe (Figma, Docs, etc)
  project_id bigint references public.projects(id) on delete cascade,
  parent_task_id bigint references public.tasks(id) on delete cascade,
  -- REMOVIDO: assignee_ids (Normalizado em task_assignees)
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create index idx_tasks_parent_task_id on public.tasks(parent_task_id);

-- 9. Tabela de Responsáveis pela Tarefa [NOVA]
create table public.task_assignees (
  task_id bigint references public.tasks(id) on delete cascade,
  profile_id bigint references public.profiles(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  primary key (task_id, profile_id)
);

-- 10. Tabela de Eventos
create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  location text,
  description text,
  category text, -- NOVO: Categoria vTools
  sub_category text, -- NOVO: Subcategoria vTools
  event_type text default 'Virtual', -- NOVO: 'Virtual' ou 'InPerson'
  host_ous text[], -- NOVO: Array de strings para Organizational Units
  is_public boolean default false, -- NOVO: Define se aparece na agenda geral (Ramo) ou apenas interna
  vtools_reported boolean default false, -- NOVO: Status do reporte vTools
  meeting_minutes_url text, -- NOVO: Link da Ata
  attendees_ieee int default 0, -- NOVO: Contagem IEEE
  attendees_guests int default 0, -- NOVO: Contagem Convidados
  attendee_list jsonb default '[]'::jsonb, -- NOVO: Lista de Presença [{id, name, type}]
  chapter_id bigint references public.chapters(id),
  project_id bigint references public.projects(id),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 11. Tabela de Classificados (Para Propostas e Ideias)
create table public.classifieds (
  id bigint generated by default as identity primary key,
  type text not null, -- 'help' (Ajuda) ou 'idea' (Ideia)
  title text not null,
  description text not null,
  image_url text,
  task_id bigint references public.tasks(id),
  responsible_id bigint references public.profiles(id) on delete set null,
  chapter_ids bigint[],
  offers_text text, -- [NOVO] Campo de texto compartilhado para ofertas
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 11.1 RPC Function to Append Offer safely
-- This allows anyone to append text without giving full UPDATE permission on the row
CREATE OR REPLACE FUNCTION public.append_classified_offer(p_classified_id bigint, p_offer_text text)
RETURNS void AS $$
BEGIN
  UPDATE public.classifieds
  SET offers_text = coalesce(offers_text, '') || E'\n\n' || p_offer_text
  WHERE id = p_classified_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 12. Tabela de Metas do Capítulo
create table public.chapter_goals (
  id bigint generated by default as identity primary key,
  chapter_id bigint references public.chapters(id) on delete cascade,
  title text not null, -- Ex: "Crescimento 2026.1"
  description text, -- Tooltip: "Aumentar membresia em 20%"
  indicator_label text not null, -- Ex: "Novos Membros"
  current_value int default 0,
  target_value int not null,
  color text default 'bg-blue-600', -- Para customização visual
  period text default 'Anual', -- 'Mensal', 'Trimestral', 'Semestral', 'Anual'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 13. Tabela de Ferramentas/Configurações
create table public.tools (
  id text primary key, -- ID Alfanumérico (ex: 'motivational_quotes', 'app_config')
  content text, -- JSON String para armazenar arrays, objetos, etc.
  status text default 'active', -- 'active', 'inactive'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 14. Tabela de Finanças (Livro Caixa)
create table public.finances (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('entry', 'exit')),
  description text not null,
  amount decimal(12, 2) not null,
  currency text not null check (currency in ('BRL', 'USD')),
  date date default CURRENT_DATE,
  invoice_url text, -- Link para comprovante (Obrigatório se type='exit' via App Logic)
  notes text, -- Anotação opcional
  chapter_id bigint references public.chapters(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null,
  created_by uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  reimbursement_status text check (reimbursement_status in ('not_required', 'requested_section', 'requested_external', 'paid')) default 'not_required'
);
